quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=move
quarkus.datasource.password=move
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/move-intranet

quarkus.hibernate-orm.database.generation=none