name: PR Check

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build e Testes
        run: ./mvnw verify   # compile + test + package

      - name: Checar vulnerabilidades
        run: ./mvnw dependency:check -q